name: Cache image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' 
jobs:
  cache-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Config
        run: |
          git config --global user.email "kj1ktk@gmail.com"
          git config --global user.name "Takuma Kajikawa"      
      - name: Download image from Vercel
        run: |
          curl -o ./images/github-readme-stats.svg 'https://github-readme-stats-git-master-valbeat.vercel.app/api?username=valbeat&show_icons=true&hide_title=true&include_all_commits=true&hide_border=true&line_height=24&show=reviews&theme=gotham'
      - name: Commit and push if there's a change
        run: |
          git add ./images/github-readme-stats.svg
          git commit -m "Update cached image" || exit 0
          git push
  purge-camo:
    runs-on: ubuntu-latest
    needs: cache-image
    steps:
      - uses: koki-develop/hub-purge-action@v1
