name: Download images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Config (Global Git Settings)
        run: |
          git config --global user.email "kj1ktk@gmail.com"
          git config --global user.name "Takuma Kajikawa"

  download-github-stats:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download GitHub Stats
        run: |
          echo "Downloading GitHub Stats..."
          curl -s -o ./github-readme-stats-api.svg \
            'https://github-readme-stats-git-master-valbeat.vercel.app/api?username=valbeat&show_icons=true&hide_title=true&hide_border=true&line_height=24&show=reviews&theme=gotham'
      - name: Upload GitHub Stats
        uses: actions/upload-artifact@v4
        with:
          name: github-stats
          path: ./github-readme-stats-api.svg

  download-top-langs:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download Top Langs
        run: |
          echo "Downloading Top Langs..."
          curl -s -o ./top-langs.svg \
            'https://github-readme-stats.vercel.app/api/top-langs/?username=valbeat&hide_title=true&theme=gotham&layout=compact&hide_border=true&langs_count=10&hide=html,css,objective-c&size_weight=0.45&count_weight=0.55'
      - name: Upload Top Langs
        uses: actions/upload-artifact@v4
        with:
          name: top-langs
          path: ./top-langs.svg

  download-holopin:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download Holopin Badges
        run: |
          echo "Downloading Holopin Badges..."
          curl -s -o ./holopin-badges.png \
            'https://holopin.me/valbeat'
      - name: Upload Holopin Badges
        uses: actions/upload-artifact@v4
        with:
          name: holopin
          path: ./holopin-badges.png

  commit-and-push:
    needs: [download-github-stats, download-top-langs, download-holopin]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./images
      - name: Config Git User
        run: |
          git config --global user.email "kj1ktk@gmail.com"
          git config --global user.name "Takuma Kajikawa"
      - name: Commit and Push Changes
        run: |
          git add ./images
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Update cached images"
          git push
